# Generated by Django 2.2.4 on 2019-11-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audios/')),
                ('textoAudio', models.TextField()),
                ('tema', models.CharField(max_length=120)),
            ],
        ),
    ]
