# Generated by Django 2.2.4 on 2019-11-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='nombre',
            field=models.CharField(default='Ninguno', max_length=120),
        ),
    ]
