# Generated by Django 2.2.4 on 2019-11-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
    ]
